name: CI Pipeline

on:
  push:
    branches:
      - main   # use master if your branch is master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Selenium tests
        run: npm test